### ISSUE TITLE
Extracting a string to arb does not auto generate localisation

### ISSUE THREAD

**Issue by milindgoel15** [lsaudon/l10nization#263]
I don't remember if this was the behaviour before as well. But should it not auto-generate the localizations of whatever string we extracted to Arb files?

After extracting it gives me:
`The getter 'setBtnText' isn't defined for the type 'AppLocalizations'.`
and I have to run `flutter gen-l10n` to update localizations. 

If this was always the behaviour, then would it be possible to do auto-generation whenever a value is extracted?

**Comment by lsaudon** [comment]
I don't use `flutter gen-l10n` because l10n.yaml exists, the options defined there will be used instead.

**Comment by milindgoel15** [comment]
I also have this file in this configuration:

```yaml
arb-dir: lib/l10n/arbs 
template-arb-file: app_en.arb 
output-dir: lib/l10n/generated 
output-localization-file: app_localization.dart 
synthetic-package: false 
nullable-getter: false
```
