### ISSUE TITLE
Autogenerated code replacing the selected string after "Excract value to arb file" doesnt include "AppLocalizations.of(context)"

### ISSUE THREAD

**Issue by PhiFry** [lsaudon/l10nization#350]
l10nization version: 3.0.1
VSCode version: 1.84.1  Mac

i10n.yaml file:
```yaml
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
```

I start with code 
```dart
final str = "Hello $i";
```

I select `"Hello $i"` then click "Excract value to arb file", I complete the form and the string gets replaced with: 
```dart
final a = l10n.hello(i);
```
I expected it to be 
```dart
final a = AppLocalizations.of(context).helloI(i);
```
